 The files belonging to this database system will be owned by user "postgres".
 This user must also own the server process.
 
 The database cluster will be initialized with locale "en_US.utf8".
 The default database encoding has accordingly been set to "UTF8".
 The default text search configuration will be set to "english".
 
 Data page checksums are disabled.
 
 fixing permissions on existing directory /var/lib/postgresql/data ... ok
 creating subdirectories ... ok
 selecting dynamic shared memory implementation ... posix
 selecting default max_connections ... 100
 selecting default shared_buffers ... 128MB
 selecting default time zone ... UTC
 creating configuration files ... ok
 running bootstrap script ... ok
 sh: locale: not found
 2025-01-29 13:53:26.960 UTC [34] WARNING:  no usable system locales were found
 performing post-bootstrap initialization ... ok
 syncing data to disk ... ok
 
 initdb: warning: enabling "trust" authentication for local connections
 You can change this by editing pg_hba.conf or using the option -A, or
 --auth-local and --auth-host, the next time you run initdb.
 
 Success. You can now start the database server using:
 
     pg_ctl -D /var/lib/postgresql/data -l logfile start
 
 waiting for server to start....2025-01-29 13:53:28.155 UTC [40] LOG:  starting PostgreSQL 13.16 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit
 2025-01-29 13:53:28.159 UTC [40] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
 2025-01-29 13:53:28.170 UTC [41] LOG:  database system was shut down at 2025-01-29 13:53:27 UTC
 2025-01-29 13:53:28.176 UTC [40] LOG:  database system is ready to accept connections
  done
 server started
 CREATE DATABASE
 
 
 /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
 
 2025-01-29 13:53:28.573 UTC [40] LOG:  received fast shutdown request
 waiting for server to shut down....2025-01-29 13:53:28.577 UTC [40] LOG:  aborting any active transactions
 2025-01-29 13:53:28.580 UTC [40] LOG:  background worker "logical replication launcher" (PID 47) exited with exit code 1
 2025-01-29 13:53:28.581 UTC [42] LOG:  shutting down
 2025-01-29 13:53:28.604 UTC [40] LOG:  database system is shut down
  done
 server stopped
 
 PostgreSQL init process complete; ready for start up.
 
 2025-01-29 13:53:28.697 UTC [1] LOG:  starting PostgreSQL 13.16 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit
 2025-01-29 13:53:28.697 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
 2025-01-29 13:53:28.698 UTC [1] LOG:  listening on IPv6 address "::", port 5432
 2025-01-29 13:53:28.712 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
 2025-01-29 13:53:28.719 UTC [55] LOG:  database system was shut down at 2025-01-29 13:53:28 UTC
 2025-01-29 13:53:28.726 UTC [1] LOG:  database system is ready to accept connections
 2025-01-29 13:53:34.647 UTC [78] ERROR:  relation "log" does not exist at character 13
 2025-01-29 13:53:34.647 UTC [78] STATEMENT:  INSERT INTO log (dttm, dag_id, task_id, event, execution_date, owner, extra) VALUES ('2025-01-29T13:53:34.626409+00:00'::timestamptz, NULL, NULL, 'cli_scheduler', NULL, 'airflow', '{"host_name": "8dd977a52b5e", "full_command": "[''/home/airflow/.local/bin/airflow'', ''scheduler'']"}') RETURNING log.id
 2025-01-29 13:53:34.845 UTC [79] ERROR:  relation "log" does not exist at character 13
 2025-01-29 13:53:34.845 UTC [79] STATEMENT:  INSERT INTO log (dttm, dag_id, task_id, event, execution_date, owner, extra) VALUES ('2025-01-29T13:53:34.809993+00:00'::timestamptz, NULL, NULL, 'cli_worker', NULL, 'airflow', '{"host_name": "831fdffd8af3", "full_command": "[''/home/airflow/.local/bin/airflow'', ''worker'']"}') RETURNING log.id
 2025-01-29 13:53:34.863 UTC [78] ERROR:  relation "job" does not exist at character 13
 2025-01-29 13:53:34.863 UTC [78] STATEMENT:  INSERT INTO job (dag_id, state, job_type, start_date, end_date, latest_heartbeat, executor_class, hostname, unixname) VALUES (NULL, 'running', 'SchedulerJob', '2025-01-29T13:53:34.860252+00:00'::timestamptz, NULL, '2025-01-29T13:53:34.860281+00:00'::timestamptz, 'NoneType', '8dd977a52b5e', 'airflow') RETURNING job.id
 2025-01-29 13:53:35.070 UTC [80] ERROR:  relation "slot_pool" does not exist at character 161
 2025-01-29 13:53:35.070 UTC [80] STATEMENT:  SELECT slot_pool.id AS slot_pool_id, slot_pool.pool AS slot_pool_pool, slot_pool.slots AS slot_pool_slots, slot_pool.description AS slot_pool_description 
 	FROM slot_pool 
 	WHERE slot_pool.slots = 1 AND slot_pool.pool = 'default_pool' 
 	 LIMIT 1
 2025-01-29 13:53:35.185 UTC [81] ERROR:  relation "log" does not exist at character 13
 2025-01-29 13:53:35.185 UTC [81] STATEMENT:  INSERT INTO log (dttm, dag_id, task_id, event, execution_date, owner, extra) VALUES ('2025-01-29T13:53:35.168000+00:00'::timestamptz, NULL, NULL, 'cli_webserver', NULL, 'airflow', '{"host_name": "96b0c18245be", "full_command": "[''/home/airflow/.local/bin/airflow'', ''webserver'']"}') RETURNING log.id
 2025-01-29 13:53:35.980 UTC [82] ERROR:  relation "log" does not exist at character 13
 2025-01-29 13:53:35.980 UTC [82] STATEMENT:  INSERT INTO log (dttm, dag_id, task_id, event, execution_date, owner, extra) VALUES ('2025-01-29T13:53:35.963326+00:00'::timestamptz, NULL, NULL, 'cli_flower', NULL, 'airflow', '{"host_name": "12b7e2ffb991", "full_command": "[''/home/airflow/.local/bin/airflow'', ''flower'']"}') RETURNING log.id
